added max paralle in matrix

diff --git a/.github/workflows/matrix.yaml b/.github/workflows/matrix.yaml
--- a/.github/workflows/matrix.yaml
+++ b/.github/workflows/matrix.yaml
@@ -12,7 +12,8 @@ jobs:
      runs-on: ubuntu-latest
 
      strategy:
-        fail-fast: false
+        # fail-fast: false
+        max-parallel:  2
         matrix:
             node-versions: [18, 19, 20]
 
@@ -37,10 +38,10 @@ jobs:
           run: |
               echo "Environment: ${{ matrix.environment }}"
               
-              if [ "${{ matrix.node-versions }}" = "19" ]; then
-                echo "Intentionally failing Node 19"
-                exit 1
-              fi
+              # if [ "${{ matrix.node-versions }}" = "19" ]; then
+              #   echo "Intentionally failing Node 19"
+              #   exit 1
+              # fi
 
         - name: Check Node Version
           run: node -v
